# Stage 1 컨테이너 (애플리케이션 빌드)
FROM golang:1.10.1-alpine3.7 as builder
COPY ./main.go ./
RUN CGO_ENABLED=0 go build -o /go-app ./main.go

# Stage 2 컨테이너 (빌드된 바이너리를 포함한 실행용 컨테이너 생성)
FROM scratch
COPY --from=builder /go-app .
ENTRYPOINT ["./go-app"]